project_id = "rpgukwjnjntdcrghyjjp"

[functions.transcribe-audio]
verify_jwt = true

[functions.analyze-conversation]
verify_jwt = true

[functions.analyze-monologue]
verify_jwt = true

[functions.generate-focus-examples]
verify_jwt = true
